# scripts/feed_discovery/sources/youtube_youtubersme.py

from __future__ import annotations

import json
import time
from collections import defaultdict
from pathlib import Path

from ..models import Candidate
from ..profiles._schema import CountryProfile, SourceConfig
from ._base import ProbeResult


class YouTubeYoutubersMeSource:
    """Youtubers.me scraped YouTube channel rankings (2026).

    Scraped from us.youtubers.me across 30 countries + 16 global categories,
    Top 1000 each. Channel IDs resolved via youtubers.me/{slug}/youtube redirect.
    All channels have verified Channel IDs and RSS feed URLs.

    Data generated by: scripts/youtubers_me_scraper.py
    Zero API calls at runtime — purely local data lookup.

    Data quality: youtubers.me is the industry-standard YouTube analytics
    aggregator. Rankings are based on subscriber counts updated regularly.
    """

    name = "youtube_youtubersme"
    DATA_PATH = (
        Path(__file__).resolve().parents[1]
        / "data"
        / "youtube_channels_youtubersme.json"
    )

    def __init__(self):
        self._by_country: dict[str, list[dict]] = defaultdict(list)
        self._channels: list[dict] = []
        self._global: list[dict] = []
        self.enabled = self.DATA_PATH.exists()
        if self.enabled:
            self._load_data()

    def _load_data(self):
        """Load the youtubers.me scraped JSON and build country index."""
        try:
            data = json.loads(self.DATA_PATH.read_text(encoding="utf-8"))
        except Exception:
            return

        channels = data.get("channels", [])
        self._channels = channels

        # Sort by subscribers descending for global ranking
        self._global = sorted(
            [ch for ch in channels if ch.get("channel_id")],
            key=lambda c: c.get("listing_stats", {}).get("subscribers_total", 0),
            reverse=True,
        )

        # Build country index: country_slug → [channel dicts]
        for ch in channels:
            cid = ch.get("channel_id", "")
            if not cid:
                continue
            for country in ch.get("countries", []):
                self._by_country[country].append(ch)

        # Sort each country's channels by subscribers descending
        for country in self._by_country:
            self._by_country[country].sort(
                key=lambda c: c.get("listing_stats", {}).get("subscribers_total", 0),
                reverse=True,
            )

    async def search(
        self,
        query: str,
        profile: CountryProfile,
        config: SourceConfig,
        session,
    ) -> list[Candidate]:
        """Return top YouTube channels for the profile's country from youtubers.me.

        The query parameter is ignored — channels are matched by country slug.
        Falls back to global top channels for countries without direct data.
        """
        if not self.enabled:
            return []

        country_slug = (profile.country or "").lower()
        candidates: list[Candidate] = []
        seen: set[str] = set()

        # Strategy 1: Direct country match (channels scraped for this country)
        channels = self._by_country.get(country_slug, [])

        # Strategy 2: Global top fallback (useful for countries not in our 30)
        if not channels:
            channels = self._global[:config.max_results]

        for ch in channels:
            cid = ch.get("channel_id", "")
            if not cid or cid in seen:
                continue
            seen.add(cid)

            subs = ch.get("listing_stats", {}).get("subscribers_total", 0)
            rank_info = f"youtubersme:{country_slug}"
            if subs:
                rank_info += f"/subs:{_fmt_subs(subs)}"

            candidates.append(Candidate(
                url=ch.get("feed_url", ""),
                category="YouTube",
                title=ch.get("channel_name", ""),
                genre="",
                national=True,
                national_reason=rank_info,
            ))

        return candidates[:config.max_results]

    async def probe(
        self,
        profile: CountryProfile,
        config: SourceConfig,
        session,
    ) -> ProbeResult:
        """Check if this source has channels for the profile's country."""
        if not self.enabled:
            return ProbeResult(
                source_name="youtube_youtubersme",
                success=False,
                result_count=0,
                latency_ms=0,
                error="disabled: data file not found",
            )

        t0 = time.monotonic()
        try:
            results = await self.search("", profile, config, session)
            elapsed = (time.monotonic() - t0) * 1000
            return ProbeResult(
                source_name="youtube_youtubersme",
                success=len(results) > 0,
                result_count=len(results),
                latency_ms=elapsed,
            )
        except Exception as e:
            elapsed = (time.monotonic() - t0) * 1000
            return ProbeResult(
                source_name="youtube_youtubersme",
                success=False,
                result_count=0,
                latency_ms=elapsed,
                error=str(e)[:200],
            )


def _fmt_subs(n: int) -> str:
    """Format subscriber count compactly: 477M, 1.2M, 850K."""
    if n >= 1_000_000:
        return f"{n / 1_000_000:.0f}M" if n % 1_000_000 < 100_000 else f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.0f}K"
    return str(n)
